name: Deploy

on:
  push:
    branches: [main, gh-pages]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actio
      - uses: actio
        with:
          path: '.'
      - uses: actio
        id: deploym
